// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MANFUCK

#ifndef _UI_COMP_BUTTONCAT_H
#define _UI_COMP_BUTTONCAT_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ButtonCat
#define UI_COMP_BUTTONCAT_BUTTONCAT 0
#define UI_COMP_BUTTONCAT_CAT2 1
#define _UI_COMP_BUTTONCAT_NUM 2
lv_obj_t * ui_ButtonCat_create(lv_obj_t * comp_parent);
void ui_event_comp_ButtonCat_ButtonCat(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
