// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MANFUCK

#ifndef _UI_COMP_PIPBOY_H
#define _UI_COMP_PIPBOY_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Pipboy
#define UI_COMP_PIPBOY_PIPBOY 0
#define _UI_COMP_PIPBOY_NUM 1
lv_obj_t * ui_Pipboy_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
