// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MANFUCK

#include "ui.h"

void ui_event_comp_ButtonCat_ButtonCat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ButtonCat = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_radio_handler(e);
    }
}

// COMPONENT ButtonCat

lv_obj_t * ui_ButtonCat_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ButtonCat;
    cui_ButtonCat = lv_btn_create(comp_parent);
    lv_obj_set_height(cui_ButtonCat, 20);
    lv_obj_set_width(cui_ButtonCat, lv_pct(161));
    lv_obj_set_align(cui_ButtonCat, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_ButtonCat, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_ButtonCat, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_ButtonCat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ButtonCat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ButtonCat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_ButtonCat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ButtonCat, lv_color_hex(0x40F58B), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_ButtonCat, 128, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(cui_ButtonCat, lv_color_hex(0x40F58B), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(cui_ButtonCat, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(cui_ButtonCat, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(cui_ButtonCat, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(cui_ButtonCat, lv_color_hex(0x40F58B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_ButtonCat, 128, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(cui_ButtonCat, lv_color_hex(0x40F58B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(cui_ButtonCat, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(cui_ButtonCat, 3, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(cui_ButtonCat, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(cui_ButtonCat, lv_color_hex(0x40F58B), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(cui_ButtonCat, 128, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(cui_ButtonCat, lv_color_hex(0x40F58B), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(cui_ButtonCat, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(cui_ButtonCat, 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(cui_ButtonCat, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t * cui_Cat2;
    cui_Cat2 = lv_label_create(cui_ButtonCat);
    lv_obj_set_width(cui_Cat2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Cat2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Cat2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Cat2, "S.P.E.C.J.A.L");
    lv_obj_set_style_text_color(cui_Cat2, lv_color_hex(0x40F58B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Cat2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Cat2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTONCAT_NUM);
    children[UI_COMP_BUTTONCAT_BUTTONCAT] = cui_ButtonCat;
    children[UI_COMP_BUTTONCAT_CAT2] = cui_Cat2;
    lv_obj_add_event_cb(cui_ButtonCat, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ButtonCat, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_ButtonCat, ui_event_comp_ButtonCat_ButtonCat, LV_EVENT_ALL, children);
    ui_comp_ButtonCat_create_hook(cui_ButtonCat);
    return cui_ButtonCat;
}

