// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MANFUCK

#ifndef _UI_COMP_OPTBUTTON_H
#define _UI_COMP_OPTBUTTON_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT OptButton
#define UI_COMP_OPTBUTTON_OPTBUTTON 0
#define UI_COMP_OPTBUTTON_OPTNAME13 1
#define UI_COMP_OPTBUTTON_OPTVAL13 2
#define _UI_COMP_OPTBUTTON_NUM 3
lv_obj_t * ui_OptButton_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
