// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MANFUCK

#include "ui.h"

// COMPONENT OptButton

lv_obj_t * ui_OptButton_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_OptButton;
    cui_OptButton = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_OptButton, lv_pct(100));
    lv_obj_set_height(cui_OptButton, lv_pct(13));
    lv_obj_set_x(cui_OptButton, -1);
    lv_obj_set_y(cui_OptButton, 6);
    lv_obj_set_align(cui_OptButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_OptButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_OptButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_OptButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_OptButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_OptButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_OptButton, lv_color_hex(0x40F58B), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(cui_OptButton, 128, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(cui_OptButton, lv_color_hex(0x40F58B), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(cui_OptButton, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(cui_OptButton, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(cui_OptButton, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t * cui_OptName13;
    cui_OptName13 = lv_label_create(cui_OptButton);
    lv_obj_set_width(cui_OptName13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_OptName13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_OptName13, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_OptName13, "Szczescie");
    lv_obj_set_style_text_color(cui_OptName13, lv_color_hex(0x40F58B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_OptName13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_OptName13, &ui_font_MONF2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_OptVal13;
    cui_OptVal13 = lv_label_create(cui_OptButton);
    lv_obj_set_width(cui_OptVal13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_OptVal13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_OptVal13, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(cui_OptVal13, "6");
    lv_obj_set_style_text_color(cui_OptVal13, lv_color_hex(0x40F58B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_OptVal13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_OptVal13, &ui_font_MONF2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_OPTBUTTON_NUM);
    children[UI_COMP_OPTBUTTON_OPTBUTTON] = cui_OptButton;
    children[UI_COMP_OPTBUTTON_OPTNAME13] = cui_OptName13;
    children[UI_COMP_OPTBUTTON_OPTVAL13] = cui_OptVal13;
    lv_obj_add_event_cb(cui_OptButton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_OptButton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_OptButton_create_hook(cui_OptButton);
    return cui_OptButton;
}

