// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MANFUCK

#include "ui.h"

// COMPONENT Pipboy

lv_obj_t * ui_Pipboy_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Pipboy;
    cui_Pipboy = lv_img_create(comp_parent);
    lv_obj_set_width(cui_Pipboy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Pipboy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Pipboy, 72);
    lv_obj_set_y(cui_Pipboy, -58);
    lv_obj_set_align(cui_Pipboy, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Pipboy, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Pipboy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PIPBOY_NUM);
    children[UI_COMP_PIPBOY_PIPBOY] = cui_Pipboy;
    lv_obj_add_event_cb(cui_Pipboy, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Pipboy, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Pipboy_create_hook(cui_Pipboy);
    return cui_Pipboy;
}

