// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MANFUCK

#include "ui.h"

void ui_event_radio_handler(lv_event_t * e)
{
	// Your code here
}
